refactor mergeMyCommandsParams function into a static class
grammyjs/commands pull request #21
Opened 2024-05-31 15:04 UTC by carafelix

Adds a little bit more clarity into what it's going on

2024-06-04 05:34 UTC, carafelix commented
Squashed deno fmt into the last commit

2024-06-04 11:15 UTC, roziscoding commented on src/commands.ts
> +     * 'Takes effect' in this case means: being displayed in the user commands menu.
This should go before the `export type` line, because it refers to the whole type

2024-06-04 11:15 UTC, roziscoding commented on src/commands.ts
> +     * If @param language_code it's defined, they will only take effect on users of that language.
These should go before each property, without the `@param` tag, because they describe the property itself.

2024-06-04 11:18 UTC, roziscoding requested changes

2024-06-04 11:18 UTC, roziscoding commented on src/commands.ts
> +     * @param commands that can be each one passed to a SetMyCommands Call
`@param` is only for function params. here we should describe each property with its own comment block, like


```ts
/** If defined, commands will only show up in this scope /**
scope?: BotCommandScope;
```

2024-06-04 11:18 UTC, roziscoding commented on src/commands.ts
> +     * 'Takes effect' in this case means: being displayed in the user commands menu.
This should go before the `export type` line, because it refers to the whole type

2024-06-04 11:18 UTC, roziscoding commented on src/commands.ts
> +     * If @param language_code it's defined, they will only take effect on users of that language.
These should go before each property, without the `@param` tag, because they describe the property itself.

2024-06-04 11:19 UTC, roziscoding commented on src/context.ts
> +     *
an `@example` section would be good here.

2024-06-10 10:43 UTC, roziscoding approved these changes

2024-06-10 10:43 UTC, roziscoding commented
Let's go ahead and merge this.
Thank you so much!

2024-06-10 18:03 UTC, merged